pipeline {
    agent any
    stages {
        stage("Checkout") {
            steps {
                git url: 'https://github.com/BigMoistLochu/KolowiumDevs2/tree/main/Zadanie2', branch: 'main'
            }
        }
        stage("Compile and Build") {
            steps {
                sh '''
                mvn compile
                '''
            }
        }

        stage("Unit Tests") {
            steps {
                sh '''
                mvn test
                '''
            }
        }

        stage("Analys Code") {
            steps {
                sh '''
                mvn verify
                '''
                publishHTML (target: [
                reportDir: 'target/site/checkstyle',
                reportFiles: 'main.html',
                reportName: "Checkstyle Report"
                ])
            }
        }
        
    }
}
